name       : sysbench
version    : 1.0.20
release    : 1
source     :
    - https://github.com/akopytov/sysbench/archive/refs/tags/1.0.20.tar.gz : e8ee79b1f399b2d167e6a90de52ccc90e52408f7ade1b9b7135727efe181347f
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Scriptable database and system performance benchmark
description: |
    sysbench is a scriptable multi-threaded benchmark tool based on LuaJIT. It is most frequently used for database benchmarks, but can also be used to create arbitrarily complex workloads that do not involve a database server.
builddeps  :
    - pkgconfig(libmariadb)
    - pkgconfig(libpq)
    - pkgconfig(libssl)
    - libaio-devel
setup      : |
    $workdir/autogen.sh
    %configure --with-pgsql --with-mysql-includes=/usr/include/mysql --sysconfdir=/usr/share/defaults
build      : |
    %make
install    : |
    %make_install
